### ISSUE TITLE
Implement minimalistic MTAG declaration 

### ISSUE THREAD

**Issue by stas-dubrovskyi** [mtag-dev/squall#53]
Explicit in place
```Python
@router.post(
    "/user",
    gw = Gateway(permission="service:user:add", group="User" title="Add")
)
async def add_user():
    return {}
```

Explicit, inherit group name
```Python
router = squall.Router(gw = Gateway(group="User"))

@router.post(
    "/user",
    gw = Gateway(permission="service:user:add", title="Add")
)
async def add_user():
    return {}
```

From handler name
```Python
@router.post("/user", gw = Gateway(permission="service:user:add"))
async def user_add(): # user_add extracted as ["User", "Add"] if no __ (double underscore defined) if defined, left part is "Group name", right is Action name
    return {}
```

Then implement endpoint which will provide entire application configuration.
Then implement on_startup hook for automatic application endpoints registration.

@KostSvitlana please review this issue scope

**Comment by KostSvitlana** [comment]
I think will be better don't use the same class for create different objects. Maybe in Router use other class like GatewayGroup or instead parameter `gw`  use `gw_group` like str.
`router = squall.Router(gw = GatewayGroup(name="User"))

@router.post(
    "/user",
    gw = Gateway(permission="service:user:add", title="Add")
)
async def add_user():
    return {}`
 or
 `router = squall.Router(gw_group="User")

@router.post(
    "/user",
    gw = Gateway(permission="service:user:add", title="Add")
)
async def add_user():
    return {}`

**Comment by stas-dubrovskyi** [comment]
```
router = squall.Router(gw = GatewayScope(group="User"))
```

**Comment by justdominator** [comment]
Let it be here

```yaml
services:
  my_service:
    ignore_trailing_slashes: true

    validators:
      int: "^[0-9]+$"
      uuid: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"

    endpoints:
      - method: "POST"
        path: "/user"
        group: "User"
        title: "Add"
        permission: "service:user:add"
        allow_anonymous: false

      - method: "GET"
        path: "/user/{user_id:int}"
        group: "User"
        title: "View"
        permission: "service:user:get"
        allow_anonymous: false

      - method: "PATCH"
        path: "/user/{user_id:int}"
        group: "User"
        title: "Edit"
        permission: "service:user:edit"
        allow_anonymous: false

      - method: "DELETE"
        path: "/user/{user_id:int}"
        group: "User"
        title: "Delete"
        permission: "service:user:delete"
        allow_anonymous: false
```
